language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  on:
    branch: master
  username: __token__
  password:
    secure: Ri0mAl5OBszbB8RZiXKQCACfM0DqJqvzvdQSATHk96gxyhyrCnMUgevs50LPNc4lZ1W82kIO78VhM2m7KuSmtBbkCbFN5kCpFu1YucMc3v1KXp9/eKOk7T9Qi0B/8VdTgOYMrbuwSGDss+Uxhg5XHNjJZbs2br08WUnpw/JmDuSQemzf2i1h/gkyMcp3tLsFnrn9b9vRJc4348KPGogfhLNJ2u+vqiej1Bdau0W8Sits2i2tPCXHAO3rD8BeJ6ZwiE9hmtTQqeSuuYlfvJN9R1EgFhCWrdtpuJIvOw17D6AW6TgcJRpHfNn4vHjDiJaQkwCG7Yg64Ai0ySeC8A+EzR78iRm/AZmiiFYSbdG642DcslYaTF2v6bF5nB9zDsZ3T9Qb6hZQD88Z8EvTxD3jtjLRpTDmnglW3fa70TEggyc+oNO4JWtzcJUjzmkRh7rGkHWCcDdm+WZlv7gdL5ymaRofv5GmDbDbgDCoi01+BooNAnTKXCgdh/LgnZnkVkVVved+Mb5LM3BQpKB+d73sWfBOwoaG3qUepzZetz/FVFjlRPK2yHbVPe1s/aJun2uQrcyUXLQ8xH2NWiFvWoO2+DBa5GE1T1LeZyR/oKc9Mg0/FaaRyDMvRDAhpSpWWovlyJzDhouE79vriSgFlLg+meLjXmHeZp82zau2Y8dqN0M=
