language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis furo
script: tox
deploy:
  provider: pypi
  on:
    branch: master
  username: youngsm
  password:
    secure: ${PYPI_PASSWORD}