language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: AFiNzWrcXpfAHZdref3W8SmkioCef3YY6g7v7YmEIrE5VXlICHA4WYX8XVur6Cnke0OoD0aLQzeO8nbqXSeWk8JQwA0k7hVqXGB+5KpEeZ/73CHXvM4+N4YRYkWTzP1yvlwBjnUeeJXYJIoM55jZOkk14pRjDK27n6Ny/ZW8xkFNtQ3RL2KDeQ0HEDhu6TjMd/4cWov35gWUArBB95GUlJFLtxn9ZXi1M7CDfP3L4ga0/+ynJ1rLRfZYblrplR/X4FIZTSpyac1jQ4mTivnmj1/NpKNdc3pA7zUVc1/R44WULn96qM3v0e56oRY12+VyJZIQeCitIa5QGTK2VjAi3qDfifhN7/dyNN9Xd1XjIZQGza1D/SzTfxPw0Xb2mNigBDlNKg5cZpwr6Fjmiw7Bu6mGMlOO77UmPL4bZezOe1G8z/He3Ci/KWxtLg16wDsq5+Gqf3f6PsADouDR139HTi8h8a9cziysVGOqBQhK5z2FGriVvk87ky7ZFgf/MS80EehNZvsTfOc5vAfS/eNq2pnaGcov6W9rG+xLZ9/zSyHkIr6FhXIlcoKuYi3aaScRb6mT5ioD3PHQ16ClZfJAvfGCDVr3HF8Pj0Ih6LlRp6EcXS0SjVTYjUdpayTyn2pokfQeEA/79zTSU28Icl309XN8M0GPI+xmp5ohsmDh38M=
  on:
    tags: true
    repo: youngsm/adsgrb
    python: 3.8
