language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  on:
    tags: true
    branch: master
  username: youngsm
  password:
    secure: mA9Q1uTPOB6TzVIjndQW5xZSzsp5rFT6KLV9BkVZ7bEbYFCrqlr+Ppm0GjeW3aL3faHD3nOhPBZ2XL2uVj30H47ypkDZgxJo/D8hP0pfVno00XrEC/ASLtk4uW8VkXOpzsTuXAMgjAukoEOaEYZiWOQ3WseGtimP4pmGtu88WLDQIj8P7Pur+jWSMNtaPzcnQZkzjnqN2zulRzbG+YvV/B3NeJ0QQ/Or3Jk5dn63ckL04cCrvam9+7ljVP304QABdcArK97A/cQj3VzmId0i5UespOAdm1F9inKZF1v/XfKm2jnp2UU8qnSfo34qkgZNKyUta9rv9llbpVdCBX5jN2C6AicyOM1FYDauWurd9fxIT6t4foB63GTv1Vl+TXBf15XbzLsbt1Y8Zyx7UTurBpQtZPImZp6hnssZ8YhlRALdjwfCAVNEJS0gIx1J5OvZkad6H2SIaVcdPT6iOXLJ3ZJrQMWOa7J/pOEHRe9vmEDjMLNeLilf825O6acb/+R06jEcDVCD1WFTPDwPrwPcuCB4JOxl9X0X0NA95o734Xyi481K7sv2I79fW9mAYI8tHF3nxFGyEaPKWLPjFpL2ddoXO8XGgLGdIYppuW+EyVHrGoYlFW4wFQb+npg65VE9OJktdcKbycSCdCYpUiDlWCa+Xr+H+urBR61m9gcnmeI=
